# Java Makefile

JAVAC = javac
SRC = MasterMind.java Seikai.java Solver.java contains.java probability.java

# デフォルトターゲット：すべてのJavaファイルをコンパイル
all:
	$(JAVAC) $(SRC)

# .class ファイルを削除
clean:
	rm -f *.class
